### ISSUE TITLE
[BUG] Player inflicts damage twice in first wave

### ISSUE THREAD

**Issue by mariofv** [OnionGalaxy/TwinlightSouls#2]
**Describe the bug**
When player deals damage to enemies in the first wave the damage is applied twice. This also causes the method `OnDeath` be called twice

**Expected behavior**
Dealing damage once.

**Comment by JoanStinson** [comment]
This is fixed on "mushdoom_fix" branch. I wasn't checking the status of the enemy in the TakeDamage method 😄
