### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by JordiRomagosa** [OnionGalaxy/TwinlightSouls#42]
**There are some things that severely affect the gameplay and need to be fixed for this VS. They are the following:**

- If you move **after** the mushdoom sets the mark for the ranged attack on the floor, the mushdoom will shot the projectile in your current position instead of where the mark was set.
- Attacking (J) while jumping stops the jump completely. Also, it makes no animation while the attack is "playing".
- The dash takes too much time after it is done until the player can move again.
- Mushdoom seek chase is antinatural, refering to the movement when going after the player.

**Describe the solution you'd like**
At least the first 3 points should be solved to have a good result for this VS. The last one will still affect the gameplay but is understandable that can't be fixed with the limited amount of time.

**Comment by Dartemiss** [comment]
Point 2 and 3 is fixed for vs3
