### ISSUE TITLE
[BUG] Starting with player 2 only breaks the level

### ISSUE THREAD

**Issue by RickyVimon** [OnionGalaxy/TwinlightSouls#43]
Just starting the game, the mushdoom attacks you and the player falls under the level (img attacthed)

**To Reproduce**
1. Select player 2 on player selection
2. Let the level start and don't move
3. After being attacked by the mushdoom, the player falls.

![bug](https://user-images.githubusercontent.com/33130090/84883819-4efa6280-b091-11ea-8a60-93c155b6bfc2.JPG)

**Comment by mariofv** [comment]
Fixed [here](https://github.com/OnionGalaxy/LittleOrionEngine/pull/184)
