### ISSUE TITLE
[BUG] Jumping towards camera in the cave

### ISSUE THREAD

**Issue by RickyVimon** [OnionGalaxy/TwinlightSouls#44]
Player gets stucked in the air with a loop animation when jumping towards the camera on the first platform in the cave

**To Reproduce**
1. Go to 'the cave
2. Jump to the first platform
3. Jump towards the camera

![caveBug](https://user-images.githubusercontent.com/33130090/84885022-bd8bf000-b092-11ea-9e00-6bc24fc41bf9.gif)

**Comment by JorxSS** [comment]
Fixed [here](https://github.com/OnionGalaxy/TwinlightSouls/pull/53)
