### ISSUE TITLE
[BUG] Hole falling level breakdown

### ISSUE THREAD

**Issue by RickyVimon** [OnionGalaxy/TwinlightSouls#46]
![WholeBug](https://user-images.githubusercontent.com/33130090/84887541-2cb71380-b096-11ea-828b-bd87b5dff1f6.gif)

**Describe the bug**

**To Reproduce**
1. Go to the hole platform, to the far plane wall
2. keep walking towards the background while the floor breaks
3. Player will fall down the level

**Comment by mariofv** [comment]
Fixed [here](https://github.com/OnionGalaxy/LittleOrionEngine/pull/184)

**Comment by JorxSS** [comment]
fixed in new release
