### ISSUE TITLE
Typography error in the credits

### ISSUE THREAD

**Issue by gerardtb1** [OnionGalaxy/TwinlightSouls#91]
![Screenshot_1](https://user-images.githubusercontent.com/56318812/87551653-f8447080-c6b0-11ea-8fac-9da45e367546.jpg)

**Comment by Pacasasgar** [comment]
I take advantage of this issue to mention that 'PAU GARCIA CASAS' is wrong. Surnames are unordered. Correct name is: 'PAU CASAS GARCIA).

**Comment by Dartemiss** [comment]
Fixed on the Alpha1 build
